### ISSUE TITLE
Prototype Token error "Cannot read properties of undefined (reading 'position')"

### ISSUE THREAD

**Issue by Doresain** [kandashi/sidebar-context#6]
Great module, thanks!

When selecting the 'Prototype Token' option I get the following error, even when sidebar-context is the only active module:

![image](https://user-images.githubusercontent.com/26096062/158522899-64c2191f-dac3-4243-82ff-ab55ccb70130.png)

**Comment by DOMtheDM** [comment]
I'm also receiving the same error with only Sidebar Context active.
